# Configuration for dependency review action
fail-on-severity: moderate
allow-dependencies-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Unicode-DFS-2016
# Add any packages to deny here
deny-packages: []
# Allow specific GitHub Security Advisories if needed
allow-ghsas: []
comment-summary-in-pr: always