# GitHub repository settings
# These settings are automatically synced by the GitHub Settings app
# App: https://github.com/apps/settings
# Last updated: 2025-09-22

repository:
  # Basic settings
  name: openai-ergonomic
  description: Ergonomic Rust wrapper around openai-client-base with builder patterns
  homepage: https://docs.rs/openai-ergonomic
  topics:
    - openai
    - gpt
    - ai
    - llm
    - chatgpt
    - rust

  # Repository settings
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  # Default branch
  default_branch: main

  # Merge settings
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  allow_update_branch: true

  # Security settings
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection
    protection:
      # Require PR reviews
      required_pull_request_reviews: null  # No required reviews for now

      # Require status checks
      required_status_checks:
        strict: true  # Require branches to be up to date before merging
        contexts:
          # Core CI checks from ci.yml workflow
          - "Format"                             # rustfmt check
          - "Clippy"                             # clippy linting
          - "Test (ubuntu-latest, stable)"      # Ubuntu stable tests
          - "Test (ubuntu-latest, beta)"        # Ubuntu beta tests
          - "Test (macos-latest, stable)"       # macOS tests
          - "Test (windows-latest, stable)"     # Windows tests
          - "Documentation"                      # cargo doc check
          - "MSRV"                              # Minimum supported Rust version

          # Build checks for different platforms
          - "Build (x86_64-unknown-linux-gnu)"
          - "Build (x86_64-apple-darwin)"
          - "Build (x86_64-pc-windows-msvc)"
          - "Build (aarch64-apple-darwin)"

          # Security checks from security.yml workflow
          - "Security Audit"                    # cargo audit
          - "Cargo Deny (advisories)"          # Advisory database check
          - "Cargo Deny (bans sources)"        # Banned dependencies check
          - "Cargo Deny (licenses)"            # License compliance check
          - "Dependency Review"                # GitHub dependency review
          - "Supply Chain Security"            # Supply chain checks
          - "License Compliance"               # License validation

          # Note: Code Coverage is informational only, not required

      # Enforce for admins
      enforce_admins: false

      # Restrict who can push
      restrictions: null

      # Other settings
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: false
      lock_branch: false
      allow_fork_syncing: false

# Labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: good first issue
    color: 7057ff
    description: Good for newcomers

  - name: help wanted
    color: 008672
    description: Extra attention is needed

  - name: release
    color: 00FF00
    description: Release-related PR or issue

  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file

  - name: automated
    color: 8B4789
    description: Automated PR from bots

  - name: release-plz
    color: 00FF00
    description: Created by release-plz bot

  - name: ci
    color: FFFF00
    description: Continuous Integration

  - name: msrv
    color: FF6B35
    description: Minimum Supported Rust Version changes