# Repository settings
# https://github.com/probot/settings

repository:
  name: openai-ergonomic
  description: An ergonomic Rust wrapper for the OpenAI API
  homepage: https://docs.rs/openai-ergonomic
  topics: openai, rust, api-client, builder-pattern, ergonomic
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  allow_update_branch: true
  use_squash_pr_title_as_default: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts:
          - "Test (ubuntu-latest, stable)"
          - "Test (ubuntu-latest, beta)"
          - "Test (ubuntu-latest, 1.82)"
          - "Test (macos-latest, stable)"
          - "Test (windows-latest, stable)"
          - "Format"
          - "Clippy"
          - "Documentation"
          - "Examples"
          - "Security Audit"
          - "Dependency Check"
          - "Secret Scanning"
      enforce_admins: false
      required_linear_history: true
      restrictions: null

# Labels
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: core-dependency
    color: b60205
    description: Updates to core dependencies that need review
  - name: security
    color: ee0701
    description: Security-related issues or updates
  - name: release
    color: 00FF00
    description: Release automation PR