coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 10%
        if_ci_failed: error

  ignore:
    - "examples/"
    - "docs/"
    - "target/"
    - "tests/"
    - "benches/"

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

flags:
  unittests:
    paths:
      - src/
    carryforward: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no