codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "30...80"

  status:
    project:
      default:
        target: auto
        threshold: 10%
        if_ci_failed: ignore
        if_not_found: success
        informational: true
        only_pulls: false

    patch:
      default:
        target: auto
        threshold: 20%
        if_ci_failed: ignore
        if_not_found: success
        informational: true
        only_pulls: false

    changes:
      default:
        informational: true

  ignore:
    - "examples/"
    - "docs/"
    - "target/"
    - "tests/"
    - "benches/"
    - "src/interceptor.rs"
    - "src/semantic_conventions.rs"

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true
  show_critical_paths: true
  show_project_coverage: true
  after_n_builds: 1
  # Show coverage even if there are no changes to code
  hide_project_coverage: false

github_checks:
  annotations: false

flags:
  unittests:
    paths:
      - src/
    carryforward: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no