edition = "2021"
max_width = 100
use_small_heuristics = "Default"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
format_strings = true
format_macro_matchers = true
use_field_init_shorthand = true
use_try_shorthand = true
match_arm_leading_pipes = "Never"